baseURL: "https://test-esa.harutiro.net/"
languageCode: ja
title: My New Hugo Site
theme: hugo-theme-stack
publishDir: "docs"

menu:
    main:
      - identifier: home
        name: Home
        url: /
        params:
          icon: home